site_name: fox766's note
site_url: https://fox766.github.io/notebook/
repo_url: https://github.com/fox766/notebook
repo_name: fox766/notebook
copyright: Copyright &copy; 2026 fox766

theme: 
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: deep purple

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: black
      accent: deep orange
  font:
    text: Comic Relief
    code: Roboto Mono
  language: zh
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.footer


markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fox766

plugins:
  - changelog

extra_css:
  - stylesheets/css/timelinecard.css
  - stylesheets/css/md.css

nav:
  - Home:
    - Welcome: index.md
    - 更新记录: changelog.md
  - CS:
    - cs61A: 
      - cs61A/index.md
      - cs61A/lec2.md
      - cs61A/lec3.md
      - cs61A/lec4.md
      - cs61A/lec5.md
      - cs61A/lec6.md
      - cs61A/lec7.md
      - cs61A/lec8.md
      - cs61A/lec9.md
      - cs61A/lec10.md
      - cs61A/lec11.md
      - cs61A/lec12.md
      - cs61A/lec15.md
      - cs61A/lec16.md
      - cs61A/lec17.md
      - cs61A/lec18.md
      - cs61A/lec19.md
      - cs61A/lec20.md
      - cs61A/lec21.md
      - cs61A/lec22.md
      - cs61A/lec23.md
      - cs61A/lec24.md
      - cs61A/lec26.md
      - cs61A/lec27.md
      - cs61A/lec28.md
      - cs61A/lec29.md
      - cs61A/lec30.md
      - cs61A/lec31.md
      - cs61A/lec32.md
      - cs61A/lec33.md
      - cs61A/lec34.md
    - cs61B:
      - cs61B/index.md



    



    